public class split {
  public static void main(String [] args)
  {
    String str = "BAABAAABBBABAAABAAABABABAAABAABAABABAABAAABAABAAAAAAABBABBABBAABAAABBBABABBAAAAAABAABAABAAAABBAABBABABBABAAABBBAABAAABBBAABAAAABABBAAAAABAAAAAAAABAAAABAAABBABAAABBABBAAAAAAABBBAAABBAABAAABBBAABAAABAAABAAAAAAABAABBABBAABBBAAAABAAABAABAAABBABAABABABABAABBABBAABBAABAABAABAAABBBAABAABAABAABAAAAAABBABAAAABBAAAABBABAAABABBABAABABAABBBAABAABAAAAAAABBAABAAAAAAABAABAAABBBAAAAAABBAAAAABBAABBBAABAABAAAAAABAAAABBBAABAABABAABAAAAABAAABAABAAABAABAAABBAABAAABBBAAAAABAABAAABBBAABAAAAABBABAAAAAABBAAAABBAABBBABBAAAAAAABBBAABBABABAAABAAABABBABABBAAABBABAABABAAAAAABBBAABBABABBABBAAAAABBBAABBABBAABAAABBBAABAAAAABAAAAAABAAAABABBAAAAAAABBAAAAABBBAABAAABBBAABAABAAAAAABAABABAAABAAABAABAAABBBAAAAAABABAAAABAAAAAAABABBAABAABAABAABBABBAABAAABBBABAAABAAABBAABBAAAAABAABBABABABAABABAABAABBABAAABBABAAAAABAAAAAAAABBAAAAABBABABAABAAAAABAABABAAABAAABAABAAABBBABAAABAABBABABAABAAAAABAABAABABABAAAABBBAABAABAAAAAABAAAAAABAABAABAABAAABBBAABAABAAABAABAAAABAAABBAAAABAAABABBABAAAAABAABAAABAAABAAAAAAABBBABAABBABABAAABAABAABAABABBABBABABBAABAABAAAAAAAABBABAABBAABAABAAABAABAAAABAABABAAAABBBAAAAABAABAAAAAABAAABAAABAABBABBAABBBAAAAAABBAAABAAABAAABAAABABABAAAAAAABAAAAAABBBAABBABBBAABBABABBAABABBAABBABBAABBBAAAAAABBBAAAAABAABAAABAABAABAAABBBAAAAABAABAAABBBAABAAAAAAABAABBAABAAABBAAAABABABAAAABBAAAAABBBAAABABABBAABAAAAAAAABBAABAAABBAABAABBABABAABABAAAABABAABABABABBAABBABBAABBBAAAAABAAAABBABBABBABAAABBABAAABAAABAABAAABBBABABAABBABBAABBAABAAAAAAAABBAAAAABBABAAAAABABABBABBAAAABABAAABAAAABBAAABAABABAAAABBAAAABBAAAAAABAABABABBAABBABBAABBBAAAAAAABBABAAABAAABAAABAABBABBAAAAAAABBBAAABBAABAABBABABBABAABBBAAAAABAABBAABAAABABAABBABBAAABBAABAAAAAAAAAABBAAAAAAAAAAAABAAABAAABBABAABABABAABABAAAABBAABAAABABABBAABAAABBAAAAAAAABABAABABAAAAAABAAAAAABAAABBBABAABBABBAAABAAABAAABAABBBAAABB";
    int alpha = 0;
    char A = 'A';
    char B = 'A';
    char C = 'A';
    char D = 'A';
    char E = 'A';
    for (int i = 0;i < str.length(); i++){
    if (alpha == 0)
    {
      A = 'A';
      B = 'A';
      C = 'A';
      D = 'A';
      E = 'A';
      A = str.charAt(i);
      alpha = alpha + 1;
    }
    else if (alpha == 1)
    {
      B = str.charAt(i);
      alpha = alpha + 1;
    }
    else if (alpha == 2)
    {
      C = str.charAt(i);
      alpha = alpha + 1;
    }
    else if (alpha == 3)
    {
      D = str.charAt(i);
      alpha = alpha + 1;
    }
    else if (alpha == 4)
    {
      E = str.charAt(i);
      alpha = 0;
      System.out.println(A + "" + B + "" + C + "" + D + "" + E);
    }
    }
  }
}
