//Created by Joseph Zhong on June of 2018 for the intended purpose of use at the Capture the Flag Challenge for UNO's GenCyber Camp.
//Joseph Zhong, though, has granted permission for this to be used elsewhere.
//
//This code is currently incomplete. This was an attempt at creating a coding solution to the a challenge I created for the CTF Challenge at UNO's GenCyber Camp.
//
//If someone can finish this code for me, I would be much thankful and credit will be given.

public class split {
  public static void main(String [] args)
  {
    String str = "BAABAAABBBABAAABAAABABABAAABAABAABABAABAAABAABAAAAAAABBABBABBAABAAABBBABABBAAAAAABAABAABAAAABBAABBABABBABAAABBBAABAAABBBAABAAAABABBAAAAABAAAAAAAABAAAABAAABBABAAABBABBAAAAAAABBBAAABBAABAAABBBAABAAABAAABAAAAAAABAABBABBAABBBAAAABAAABAABAAABBABAABABABABAABBABBAABBAABAABAABAAABBBAABAABAABAABAAAAAABBABAAAABBAAAABBABAAABABBABAABABAABBBAABAABAAAAAAABBAABAAAAAAABAABAAABBBAAAAAABBAAAAABBAABBBAABAABAAAAAABAAAABBBAABAABABAABAAAAABAAABAABAAABAABAAABBAABAAABBBAAAAABAABAAABBBAABAAAAABBABAAAAAABBAAAABBAABBBABBAAAAAAABBBAABBABABAAABAAABABBABABBAAABBABAABABAAAAAABBBAABBABABBABBAAAAABBBAABBABBAABAAABBBAABAAAAABAAAAAABAAAABABBAAAAAAABBAAAAABBBAABAAABBBAABAABAAAAAABAABABAAABAAABAABAAABBBAAAAAABABAAAABAAAAAAABABBAABAABAABAABBABBAABAAABBBABAAABAAABBAABBAAAAABAABBABABABAABABAABAABBABAAABBABAAAAABAAAAAAAABBAAAAABBABABAABAAAAABAABABAAABAAABAABAAABBBABAAABAABBABABAABAAAAABAABAABABABAAAABBBAABAABAAAAAABAAAAAABAABAABAABAAABBBAABAABAAABAABAAAABAAABBAAAABAAABABBABAAAAABAABAAABAAABAAAAAAABBBABAABBABABAAABAABAABAABABBABBABABBAABAABAAAAAAAABBABAABBAABAABAAABAABAAAABAABABAAAABBBAAAAABAABAAAAAABAAABAAABAABBABBAABBBAAAAAABBAAABAAABAAABAAABABABAAAAAAABAAAAAABBBAABBABBBAABBABABBAABABBAABBABBAABBBAAAAAABBBAAAAABAABAAABAABAABAAABBBAAAAABAABAAABBBAABAAAAAAABAABBAABAAABBAAAABABABAAAABBAAAAABBBAAABABABBAABAAAAAAAABBAABAAABBAABAABBABABAABABAAAABABAABABABABBAABBABBAABBBAAAAABAAAABBABBABBABAAABBABAAABAAABAABAAABBBABABAABBABBAABBAABAAAAAAAABBAAAAABBABAAAAABABABBABBAAAABABAAABAAAABBAAABAABABAAAABBAAAABBAAAAAABAABABABBAABBABBAABBBAAAAAAABBABAAABAAABAAABAABBABBAAAAAAABBBAAABBAABAABBABABBABAABBBAAAAABAABBAABAAABABAABBABBAAABBAABAAAAAAAAAABBAAAAAAAAAAAABAAABAAABBABAABABABAABABAAAABBAABAAABABABBAABAAABBAAAAAAAABABAABABAAAAAABAAAAAABAAABBBABAABBABBAAABAAABAAABAABBBAAABB";
    int alpha = 0;
    char A = 'A';
    char B = 'A';
    char C = 'A';
    char D = 'A';
    char E = 'A';
    for (int i = 0;i < str.length(); i++){
    if (alpha == 0)
    {
      A = 'A';
      B = 'A';
      C = 'A';
      D = 'A';
      E = 'A';
      A = str.charAt(i);
      alpha = alpha + 1;
    }
    else if (alpha == 1)
    {
      B = str.charAt(i);
      alpha = alpha + 1;
    }
    else if (alpha == 2)
    {
      C = str.charAt(i);
      alpha = alpha + 1;
    }
    else if (alpha == 3)
    {
      D = str.charAt(i);
      alpha = alpha + 1;
    }
    else if (alpha == 4)
    {
      E = str.charAt(i);
      alpha = 0;
      System.out.println(A + "" + B + "" + C + "" + D + "" + E);
    }
    }
  }
}
